# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-07-03 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.IntegerField(verbose_name='订单的总金额'),
        ),
        migrations.AlterField(
            model_name='order',
            name='house_price',
            field=models.IntegerField(verbose_name='房屋的单价'),
        ),
    ]
